### ISSUE TITLE
[Crash] 1.18.1 mods report incompatibility with core lib

### ISSUE THREAD

**Issue by tophlove** [SuperMartijn642/SuperMartijn642sCoreLib#50]
**Version Info**
- Minecraft, 1.18.1
- Core Lib, (1.1.12b), super...lib-1.1.12b-fabric-mc1.18.jar

**Steps to Reproduce**
...I'm currently trying to get your backpack mod to work, but i have the same issue when i tried your wormhole mod (both of which i absolutely love btw <3). So to reproduce the issue I'd add the backpack mod to my 1.18.1 profile in curse (packedup-1.0.30-fabric-mc1.18.jar). Then when trying to load the game, it crashes after pressing "Play" on the launcher. Here is the text that is displayed after it crashes:

"Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'SuperMartijn642's Core Lib' (supermartijn642corelib) 1.1.12b with any version between 1.1.0 (inclusive) and 1.2.0 (exclusive).
Unmet dependency listing:
	 - Mod 'Packed Up' (packedup) 1.0.30 requires any version between 1.1.0 (inclusive) and 1.2.0 (exclusive) of mod 'SuperMartijn642's Core Lib' (supermartijn642corelib), but only the wrong version is present: 1.1.12b!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
"

**Crash report (~/logs/latest.log)**
I'm sorry, but i dug and dug around my computer and couldn't find the logs for minecraft. I'm using curse to launch the game and i just couldn't seem to find them. I will keep digging and post them when i can find them. Thanks in advance for anything you can do to get these mods up and running for this profile. I love playing with them!

**Comment by SuperMartijn642** [comment]
Not sure what went wrong with the 1.18 upload, but rebuilding the jar seems to have fixed it.
Should now work with the reuploaded version.
Thank you for reporting the issue!

> I'm using curse to launch the game and i just couldn't seem to find them.

For future reference, you can access the profile's files by right-clicking on the profile and then selecting 'Open Folder' 🙂
![image](https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/assets/12382965/96e0c80e-9537-447b-ab88-a3f4e4be9f67)

**Comment by tophlove** [comment]
Hello again. I thought opening another issue, but i figured you'd probably see this in here, and its still related to 1.18.1. 

I can't seem to get your mods to work on 1.18.1. To be fair I tried the backpack one maybe yesterday, and couldn't get it to work. I figured today I would try to get the wormhole one going since its my absolute favorite. I'm still getting game crash after I press "play" on the launcher. I made a fresh profile so that it doesn't have any other mods in case it was a compatibility issue. Also thanks for showing me how to find the game files. Here's the log for the crash:
"

[17:42:58] [main/INFO]: Loading Minecraft 1.18.1 with Fabric Loader 0.14.22
[17:42:58] [main/INFO]: Loading 54 mods:
	- cloth-config 6.5.102
	   \-- cloth-basic-math 0.6.1
	- fabric 0.46.6+1.18
	   |-- fabric-api-base 0.4.2+d7c144a865
	   |-- fabric-api-lookup-api-v1 1.5.3+d7c144a865
	   |-- fabric-biome-api-v1 6.0.2+d7c144a865
	   |-- fabric-blockrenderlayer-v1 1.1.10+3ac43d9565
	   |-- fabric-command-api-v1 1.1.7+d7c144a865
	   |-- fabric-commands-v0 0.2.6+b4f4f6cd65
	   |-- fabric-containers-v0 0.1.19+d7c144a865
	   |-- fabric-content-registries-v0 0.4.9+d7c144a865
	   |-- fabric-crash-report-info-v1 0.1.9+3ac43d9565
	   |-- fabric-dimensions-v1 2.1.10+a1d9bbf565
	   |-- fabric-entity-events-v1 1.4.6+d7c144a865
	   |-- fabric-events-interaction-v0 0.4.17+d7c144a865
	   |-- fabric-events-lifecycle-v0 0.2.9+d7c144a865
	   |-- fabric-game-rule-api-v1 1.0.11+d7c144a865
	   |-- fabric-item-api-v1 1.3.1+691a79b565
	   |-- fabric-item-groups-v0 0.3.7+3ac43d9565
	   |-- fabric-key-binding-api-v1 1.0.9+d7c144a865
	   |-- fabric-keybindings-v0 0.2.7+b4f4f6cd65
	   |-- fabric-lifecycle-events-v1 1.4.13+713c266865
	   |-- fabric-loot-tables-v1 1.0.9+d7c144a865
	   |-- fabric-mining-level-api-v1 1.0.7+d7c144a865
	   |-- fabric-mining-levels-v0 0.1.12+b4f4f6cd65
	   |-- fabric-models-v0 0.3.4+d7c144a865
	   |-- fabric-networking-api-v1 1.0.19+d7c144a865
	   |-- fabric-networking-v0 0.3.6+b4f4f6cd65
	   |-- fabric-object-builder-api-v1 1.11.5+737332ce65
	   |-- fabric-object-builders-v0 0.7.13+d7c144a865
	   |-- fabric-particles-v1 0.2.10+526dc1ac65
	   |-- fabric-registry-sync-v0 0.9.2+ad01bfbd65
	   |-- fabric-renderer-api-v1 0.4.11+b0b66fc365
	   |-- fabric-renderer-indigo 0.4.15+6825030165
	   |-- fabric-renderer-registries-v1 3.2.10+b4f4f6cd65
	   |-- fabric-rendering-data-attachment-v1 0.3.5+d7c144a865
	   |-- fabric-rendering-fluids-v1 0.1.19+3ac43d9565
	   |-- fabric-rendering-v0 1.1.12+b4f4f6cd65
	   |-- fabric-rendering-v1 1.10.6+713c266865
	   |-- fabric-resource-conditions-api-v1 1.0.2+d7c144a865
	   |-- fabric-resource-loader-v0 0.4.15+8906aafd65
	   |-- fabric-screen-api-v1 1.0.8+d7c144a865
	   |-- fabric-screen-handler-api-v1 1.1.12+d7c144a865
	   |-- fabric-structure-api-v1 2.1.3+d7c144a865
	   |-- fabric-tag-extensions-v0 1.2.9+d7c144a865
	   |-- fabric-textures-v0 1.0.10+3ac43d9565
	   |-- fabric-tool-attribute-api-v1 1.3.9+fb3b57b465
	   \-- fabric-transfer-api-v1 1.5.10+c329913d65
	- fabricloader 0.14.22
	- java 17
	- minecraft 1.18.1
	- supermartijn642configlib 1.1.8
	- supermartijn642corelib 1.1.12+b
	- wormhole 1.1.15
[17:42:58] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/Paul/Documents/Twitch/Minecraft/Install/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[17:42:58] [main/INFO]: Compatibility level set to JAVA_16
[17:42:58] [main/INFO]: Compatibility level set to JAVA_17
[17:42:58] [main/WARN]: Reference map 'supermartijn642configlib.mixins.refmap.json' for supermartijn642configlib.mixins.json could not be read. If this is a development environment you can ignore this message
[17:42:58] [main/WARN]: Error loading class: net/minecraft/class_6880$class_6883 (java.lang.ClassNotFoundException: net/minecraft/class_6880$class_6883)
[17:42:58] [main/WARN]: @Mixin target net.minecraft.class_6880$class_6883 was not found supermartijn642corelib.mixins.json:HolderReferenceMixin from mod supermartijn642corelib
[17:42:58] [main/WARN]: Error loading class: net/fabricmc/fabric/impl/datagen/FabricDataGenHelper (java.lang.ClassNotFoundException: net/fabricmc/fabric/impl/datagen/FabricDataGenHelper)
[17:42:58] [main/WARN]: @Mixin target net.fabricmc.fabric.impl.datagen.FabricDataGenHelper was not found supermartijn642corelib.mixins.json:FabricDataGenHelperMixin from mod supermartijn642corelib
[17:42:58] [main/WARN]: Error loading class: net/minecraft/class_6880$class_6883 (java.lang.ClassNotFoundException: net/minecraft/class_6880$class_6883)
[17:42:59] [main/ERROR]: Mixin apply for mod supermartijn642corelib failed supermartijn642corelib.mixins.json:MappedRegistryMixin from mod supermartijn642corelib -> net.minecraft.class_2370: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow field field_36464 was not located in the target class net.minecraft.class_2370. Using refmap supermartijn642corelib.mixins.refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field field_36464 was not located in the target class net.minecraft.class_2370. Using refmap supermartijn642corelib.mixins.refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:624) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:302) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) [sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) [fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) [fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) [fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) [fabric-loader-0.14.22.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) [?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) [?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) [?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:153) [fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) [fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) [fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) [fabric-loader-0.14.22.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:155) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) [fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.22.jar:?]
[17:42:59] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2370 failed
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.22.jar:?]
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2370 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.22.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:153) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.22.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:155) ~[fabric-loader-0.14.22-1.18.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.22.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:153) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.22.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:155) ~[fabric-loader-0.14.22-1.18.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [supermartijn642corelib.mixins.json:MappedRegistryMixin from mod supermartijn642corelib] from phase [DEFAULT] in config [supermartijn642corelib.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.22.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:153) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.22.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:155) ~[fabric-loader-0.14.22-1.18.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field field_36464 was not located in the target class net.minecraft.class_2370. Using refmap supermartijn642corelib.mixins.refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:624) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:302) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.22.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:153) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.22.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:155) ~[fabric-loader-0.14.22-1.18.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	... 2 more


" 

Thanks in advance for anything you can to do help me get this up and running on my server. I really appreciate it <3

**Comment by SuperMartijn642** [comment]
Probably caused by some difference between 1.18.1 and 1.18.2. I only develop for the latest subversions (so 1.18.2 in this case). Since the differences between subversions are usually somewhat small, I mark the files as compatible with all and they may or may not work.

Fixing this would require me to make a separate version specifically for 1.18.1 which I don't want to do for a couple of reasons:
- I already maintain and update 14 different versions, every version just adds to time it takes me to do updates
- I don't really see any reason not to just update to 1.18.2
- hardly anyone still plays on 1.18.1, so a separate version would see very little use

**Comment by tophlove** [comment]
Totally understand. The only reason I spun up a 1.18.1 server is to use a specific mod that changes gravity to come from a different direction. I figure since I'd be playing it a fair amount I'd try to get my favorite mods on it. 

Anywhoo. Thanks again for all you do, and thanks for taking the time to give me a response. Take care!
